CREATE TABLE moon_phases (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  phase_name varchar(100) NOT NULL,
  phase_date date NOT NULL,
  phase_time time NOT NULL,
  zodiac_sign varchar(32) NOT NULL,
  ritual_suggestion text NOT NULL,
  affirmation text NOT NULL
);
